### ISSUE TITLE
wibotic_msg cannot be used by C++ projects

### ISSUE THREAD

**Issue by barulicm-ms** [wibotic/wibotic-ros-can-connector#3]
An errant declaration in wibotic_msg's CMakeLists.txt causes CMake to error out during configuration. 

The wibotic_msg CMakeLists.txt declares in `catkin_package()` that it exports a library called `wibotic_msgs` despite no target with that name being declared in the project. This causes CMake to complain that it cannot find a target with the name `wibotic_msgs`. Removing this part of the call to `catkin_package()` resolves the issue.

**Comment by wiboticalex** [comment]
Merged. Thanks for reporting.
